name: SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available.
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
         dotnet-version: '7.0.x'
      - name: Install Unity Analyzers
        run: |
          # Define paths
           $unityAnalyzersPath = 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\Microsoft\Visual Studio Tools for Unity\Analyzers'
    
          # Ensure the directory exists
          if (-not (Test-Path $unityAnalyzersPath)) {
            New-Item -ItemType Directory -Path $unityAnalyzersPath
          }
          # Download the NuGet package and extract the DLL
           nuget install Microsoft.Unity.Analyzers -OutputDirectory .\path\to\nuget-packages
           $dllPath = Get-ChildItem .\path\to\nuget-packages -Recurse -Filter 'Microsoft.Unity.Analyzers.dll' | Select-Object -ExpandProperty FullName
          # Copy Microsoft.Unity.Analyzers.dll to the target directory
          Copy-Item -Path .\path\to\Microsoft.Unity.Analyzers.dll -Destination $unityAnalyzersPath -Force
      - name: Restore dependencies
        run: dotnet restore .\ChatGptForUnity\ChatGptForUnity.sln
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v3
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
          dotnet new globaljson --sdk-version 7.0.407 --force
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"Mr-WangMingfei_ChatGptForUnity" /o:"mr-wangmingfei" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
           dotnet build .\ChatGptForUnity\ChatGptForUnity.sln
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
